### ISSUE TITLE
simulation is not exiting on `cupy.cuda.memory.OutOfMemoryError`

### ISSUE THREAD

**Issue by hightower8083** [fbpic/fbpic#520]
following the discussion in Slack :

I've also my own little question about cuda out-of-memory situation. When FBPIC runs out of GPU memory, it's not exiting but keeps hanging in a running state. We've discussed this behaviour once and if I remember correctly in such case it transfers simulation to the host memory, which is practically equivalent to stop.
When running on cluster it results in some confusion -- if code eventually gets out-of-memory in a long scan, it keeps consuming computation hours until I notice it (by checking frozen out_logs) and shut it down manually, or it hits the time-limit.
Is there a simple way to prevent this migration to the host memory and just crash instead ?

Here is the  [error file](https://github.com/fbpic/fbpic/files/6136901/err_1439400.e.txt) from the job manager

**Comment by RemiLehe** [comment]
Thanks a lot for reporting this issue!
Would you have time to install [this branch](https://github.com/fbpic/fbpic/pull/521) and re-try the above-mentioned simulation? In principle, this PR should fix your issue.

**Comment by hightower8083** [comment]
I confirm that issue is now resolved -- it returns a proper out-of-memory message and quits the simulation.
Thanx a lot @RemiLehe !
closing the issue
