### ISSUE TITLE
fbpic not using GPU resources on local machine

### ISSUE THREAD

**Issue by markomayr** [fbpic/fbpic#527]
Hi all,

I hope this is the correct platform to ask this question. I am new to using fbpic and was wondering whether people are using the code on **local discrecte GPU**s? 
I am running one of the test simulations with "use_cuda = True" but it seems like **none of the GPU resources are used by the code**. Has anyone had this problem before? I use a "NVIDIA GeForce GTX 1650" graphics card.

Cheers!

This is my env: 
# Name                    Version                   Build  Channel
appdirs                   1.4.4                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
blas                      1.0                         mkl
ca-certificates           2021.1.19            haa95532_1
certifi                   2020.12.5        py37haa95532_0
colorama                  0.4.4                    pypi_0    pypi
cudatoolkit               11.0.221             h74a9793_0
cupy-cuda100              8.6.0                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
fastrlock                 0.6                      pypi_0    pypi
fbpic                     0.19.1                   pypi_0    pypi
h5py                      2.10.0           py37h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
imageio                   2.9.0                    pypi_0    pypi
importlib-metadata        3.7.3                    pypi_0    pypi
intel-openmp              2020.2                      254
ipython                   7.21.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
llvmlite                  0.36.0           py37h34b8924_4
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib                3.4.0                    pypi_0    pypi
meshio                    4.3.11                   pypi_0    pypi
mkl                       2020.2                      256
mkl-service               2.3.0            py37h196d8e1_0
mkl_fft                   1.3.0            py37h46781fe_0
mkl_random                1.1.1            py37h47e9c7a_0
mpi                       1.0                       msmpi    conda-forge
mpi4py                    3.0.3            py37h2f6e822_5    conda-forge
msmpi                     10.1.1               h3502643_2    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
numba                     0.53.0           py37hf11a4ad_0
numpy                     1.19.2           py37hadc3359_0
numpy-base                1.19.2           py37ha3acd2a_0
openpmd-viewer            1.1.0                    pypi_0    pypi
openssl                   1.1.1k               h2bbff1b_0
parso                     0.8.1                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.1.2                    pypi_0    pypi
pip                       21.0.1           py37haa95532_0
prompt-toolkit            3.0.18                   pypi_0    pypi
pygments                  2.8.1                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyreadline                2.1                      py37_1
python                    3.7.10               h6244533_0
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pyvista                   0.29.0                   pypi_0    pypi
scipy                     1.6.2            py37h14eb087_0
scooby                    0.5.6                    pypi_0    pypi
setuptools                52.0.0           py37haa95532_0
six                       1.15.0           py37haa95532_0
sqlite                    3.35.2               h2bbff1b_0
tqdm                      4.59.0                   pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
transforms3d              0.3.1                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
vtk                       9.0.1                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2                      py37_0
zipp                      3.4.1                    pypi_0    pypi
zlib                      1.2.11               h62dcd97_4

cuda version:
![Capture](https://user-images.githubusercontent.com/34068017/112759228-155f6c00-8fc0-11eb-9bda-23add08618fb.PNG)

**Comment by MKirchen** [comment]
Hey,

if you want to use your local GPU, you have to make sure that its not used by the OS, i.e., in your case Windows should not use it for display. Also note that we do not officially support Windows (although FBPIC should/could work nonetheless).

You can try to check if numba detects and uses the GPU by calling the following commands (see [here](https://numba.pydata.org/numba-doc/dev/cuda-reference/host.html#numba.cuda.is_available)):
```
from numba import cuda
cuda.is_available()
cuda.detect()
```

I hope this helps,
Manuel

**Comment by markomayr** [comment]
Hi Manuel,

Thanks for your quick reply and the suggestion about the OS. It seems like numba detects the GPU without problem.
![Capture](https://user-images.githubusercontent.com/34068017/112764706-e35a0400-8fd7-11eb-9f40-64782c8b3b5f.PNG)
Is there anything else that I could try in order to get it to use it?

Best,
Marko

**Comment by MKirchen** [comment]
Okay, can you also check:

```
import cupy
cupy.is_available()
```

**Comment by MKirchen** [comment]
Also, you can pass `verbose_level = 2` to the `Simulation` object to get detailed information. This will also show you if the simulation is running on GPU or not.

**Comment by tom48701** [comment]
I'm not sure, but could it be that the versions of `cudatoolkit` and `cupy-cuda` need to be matched? i.e. using `cupy-cuda110` to match your version 11.0.x of `cudatoolkit` rather than `cupy-cuda100`?

Also, regarding Manuel's comment;

> if you want to use your local GPU, you have to make sure that its not used by the OS, i.e., in your case Windows should not use it for display. 

This is surprising to me, as I use FBPIC on windows also, and I have not noticed any issues using my GPU to compute while it is also displaying my desktop!

**Comment by MKirchen** [comment]
@tom48701 Okay, Thanks for the information! This used to be the case some time ago, but apparently this is not an issue anymore. I never use a local GPU, so I can only be of limited help here.

**Comment by markomayr** [comment]
Thanks both for your comments! It's encouraging that it works for you @tom48701. I have updated to cupy-cuda110 but the problem seems to persist.
Cupy is available. Passing the verbose level gives:

`FBPIC (0.19.1)

MPI available: Yes
MPI processes used: 1
MPI Library Information:
Microsoft MPI 10.1.12498.16 [PRE-RELEASE]
CUDA available: Yes
Compute architecture: GPU (CUDA)
CUDA GPUDirect (MPI) enabled: No
FBPIC selected a GeForce GTX 1650 with Max-Q Design GPU with id 0

PSATD stencil order: infinite
Particle shape: linear
Longitudinal boundaries: open
Transverse boundaries: reflective
Guard region size: 64 cells
Damping region size: 64 cells
Injection region size: 32 cells
Particle exchange period: every 14 step
Boosted frame: False

Initializing laser pulse on the mesh...
Done.`

This indicates to me that it is indeed trying to use the GPU. However, it is still running at 0% utilization and one particular CPU core seems to take the simulation load.

**Comment by MKirchen** [comment]
Looks like the GPU is used correctly. Can you maybe increase the grid size and simulation iterations, and then double check again that there is really no GPU utilization while the step loop is executing.

**Comment by tom48701** [comment]
One CPU core with high activity is normal if it's running on GPU, so that's hopeful! 
Does task manager show any cuda activity or GPU memory usage? It may be that `nvidia-smi` is not reporting correctly, I say that because it doesn't show any active processes on the GPU at all, when afaik there should always be some running to handle desktop rendering and such.

**Comment by markomayr** [comment]
It seems to work now, thanks for your help!
I'm not sure whether it was the cupy version or just the fact that the usage was too small to see it - when increasing the grid size I see that the GPU memory rises now and I can quite quickly run out of memory when adding a few zeros.

I'm going to close the issue now.
