### ISSUE TITLE
Cuda error

### ISSUE THREAD

**Issue by plasmahomie** [fbpic/fbpic#720]
Hi developers,

I have just added a comment to a previously closed issue regarding failed fbpic runs due to cuda api errors. Since I can't reopen the issue I just wanted to make a new one here to make sure it isn't missed. See below and the original issue thread ([#418](https://github.com/fbpic/fbpic/issues/418#)) for info.

I have realised also that although I say below that the error I have and the error reported in thread #418 are identical there is actually a difference in the final line. abanetto got a CUDA_ERROR_INVALID_DEVICE error where I have a CUDA_ERROR_UNKNOWN.

Thank you!

> Hi developers,
> 
> I would like to reopen this issue as I have had the exact same error when running fbpic on gpus on a cluster, both when running an fbpic simulation and when running the test.py script above. So far I have only had this issue running on the 'gpuplus' partition of my cluster, which uses nVidia H100 GPUs, and not on the 'gpu' partition, which uses nVidia A40 GPUs, if this is maybe relevant. I am currently queued to test this properly on the A40 GPUs and will update with the result.
> 
> I have successfully run fbpic several times on both GPU types, so this is an issue that occurs randomly. This would be consistent with the GPU number issue described above.
> 
> This is the error I have, identical to above:
> ```
> Traceback (most recent call last):
>   File "/mnt/scratch/users/rnr512/fbpic/test.py", line 8, in <module>
>     cuda.select_device(i_gpu)
>   File "/users/rnr512/scratch/anaconda3/lib/python3.12/site-packages/numba/cuda/api.py", line 437, in select_device
>     context = devices.get_context(device_id)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/users/rnr512/scratch/anaconda3/lib/python3.12/site-packages/numba/cuda/cudadrv/devices.py", line 220, in get_context
>     return _runtime.get_or_create_context(devnum)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/users/rnr512/scratch/anaconda3/lib/python3.12/site-packages/numba/cuda/cudadrv/devices.py", line 144, in get_or_create_context
>     return self._activate_context_for(devnum)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/users/rnr512/scratch/anaconda3/lib/python3.12/site-packages/numba/cuda/cudadrv/devices.py", line 177, in _activate_context_for
>     newctx = gpu.get_primary_context()
>              ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/users/rnr512/scratch/anaconda3/lib/python3.12/site-packages/numba/cuda/cudadrv/driver.py", line 671, in get_primary_context
>     driver.cuDevicePrimaryCtxRetain(byref(hctx), self.id)
>   File "/users/rnr512/scratch/anaconda3/lib/python3.12/site-packages/numba/cuda/cudadrv/driver.py", line 327, in safe_cuda_api_call
>     self._check_ctypes_error(fname, retcode)
>   File "/users/rnr512/scratch/anaconda3/lib/python3.12/site-packages/numba/cuda/cudadrv/driver.py", line 395, in _check_ctypes_error
>     raise CudaAPIError(retcode, msg)
> numba.cuda.cudadrv.driver.CudaAPIError: [999] Call to cuDevicePrimaryCtxRetain results in CUDA_ERROR_UNKNOWN
> 
> ``` 

 _Originally posted by @plasmahomie in [#418](https://github.com/fbpic/fbpic/issues/418#issuecomment-2946333949)_

**Comment by RemiLehe** [comment]
Thanks for raising this issue.

Have you tried using the solution implemented by @delaossa in https://github.com/fbpic/fbpic/pull/719?
In order to do so, you would need to reinstall FBPIC from the Github repository directly:
```
pip uninstall fbpic
pip install git+https://github.com/fbpic/fbpic
```
as well as `pynvml`:
```
conda install -c conda-forge pynvml
```

**Comment by plasmahomie** [comment]
Thanks for your help!

I tried reinstalling and using pynvml as described above, but I still get the same error when running fbpic.

Looking closer, my error occurs the line before the get_uuid error addressed in #719, in the line cuda.select_device(i_gpu) (line 308 of fbpic/utils/cuda.py).

```
  for i_gpu in range(n_gpus):
      if rank%n_gpus == i_gpu:
          cuda.select_device(i_gpu) <-- error in this call
          if pynvml_installed:
              uuid = get_uuid_alt(i_gpu)
          else:
              uuid = get_uuid(i_gpu)
```

I tried updating numba to the latest version but this made no difference. Let me know of any other ideas! I will discuss with my cluster managers to see if this is an issue on that side in the meantime.

**Comment by plasmahomie** [comment]
I did a full reinstall of my anaconda environment and haven't had the error again yet. This may just be chance but I have run successfully over 10 times since updating so seems promising. It's unclear what helped as there weren't newer versions of any obvious packages.

The commands for the installation were:
- `wget https://repo.anaconda.com/archive/Anaconda3-2024.10-1-Linux-x86_64.sh`
- `bash Anaconda3-2024.10-1-Linux-x86_64.sh`

Then after activating the environment:
- `conda install -n base libarchive -c main --force-reinstall --solver classic` (to fix incompatibility issue between libarchive packages from defaults and conda-forge channels, probably not necessary with newer versions)
- `conda install -c conda-forge numba scipy h5py mkl mpi4py`
- `conda install -c conda-forge cupy cuda-version=12.2 cuda-nvcc cuda-nvrtc`
- `pip install git+https://github.com/fbpic/fbpic`

And the results of `conda list` are:
```
# Name                    Version                   Build  Channel
_anaconda_depends         2024.10             py312_mkl_0  
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                  3_kmp_llvm    conda-forge
aiobotocore               2.12.3          py312h06a4308_0  
aiohappyeyeballs          2.4.0           py312h06a4308_0  
aiohttp                   3.10.5          py312h5eee18b_0  
aioitertools              0.7.1              pyhd3eb1b0_0  
aiosignal                 1.2.0              pyhd3eb1b0_0  
alabaster                 0.7.16          py312h06a4308_0  
altair                    5.0.1           py312h06a4308_0  
anaconda-anon-usage       0.4.4           py312hfc0e8ea_100  
anaconda-catalogs         0.2.0           py312h06a4308_1  
anaconda-client           1.12.3          py312h06a4308_0  
anaconda-cloud-auth       0.5.1           py312h06a4308_0  
anaconda-navigator        2.6.3           py312h06a4308_0  
anaconda-project          0.11.1          py312h06a4308_0  
annotated-types           0.6.0           py312h06a4308_0  
anyio                     4.2.0           py312h06a4308_0  
aom                       3.6.0                h6a678d5_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
archspec                  0.2.3              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0          py312h5eee18b_0  
arrow                     1.2.3           py312h06a4308_1  
arrow-cpp                 16.1.0               hc1eb8f0_0  
astroid                   2.14.2          py312h06a4308_0  
astropy                   6.1.3           py312h5eee18b_0  
astropy-iers-data         0.2024.9.2.0.33.23 py312h06a4308_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
async-lru                 2.0.4           py312h06a4308_0  
atomicwrites              1.4.0                      py_0  
attr                      2.5.1                h166bdaf_1    conda-forge
attrs                     23.1.0          py312h06a4308_0  
automat                   20.2.0                     py_0  
autopep8                  2.0.4              pyhd3eb1b0_0  
aws-c-auth                0.6.19               h5eee18b_0  
aws-c-cal                 0.5.20               hdbd6064_0  
aws-c-common              0.8.5                h5eee18b_0  
aws-c-compression         0.2.16               h5eee18b_0  
aws-c-event-stream        0.2.15               h6a678d5_0  
aws-c-http                0.6.25               h5eee18b_0  
aws-c-io                  0.13.10              h5eee18b_0  
aws-c-mqtt                0.7.13               h5eee18b_0  
aws-c-s3                  0.1.51               hdbd6064_0  
aws-c-sdkutils            0.1.6                h5eee18b_0  
aws-checksums             0.1.13               h5eee18b_0  
aws-crt-cpp               0.18.16              h6a678d5_0  
aws-sdk-cpp               1.10.55              h721c034_0  
babel                     2.11.0          py312h06a4308_0  
bcrypt                    3.2.0           py312h5eee18b_1  
beautifulsoup4            4.12.3          py312h06a4308_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
binutils_impl_linux-64    2.40                 h5293946_0  
binutils_linux-64         2.40                 hb3c18ed_9    conda-forge
black                     24.8.0          py312h06a4308_0  
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd3eb1b0_0  
blinker                   1.6.2           py312h06a4308_0  
blosc                     1.21.5               hc2324a3_1    conda-forge
bokeh                     3.6.0           py312h06a4308_0  
boltons                   23.0.0          py312h06a4308_0  
boost-cpp                 1.82.0               hdb19cb5_2  
botocore                  1.34.69         py312h06a4308_0  
bottleneck                1.3.7           py312ha883a20_0  
brotli                    1.0.9                h5eee18b_8  
brotli-bin                1.0.9                h5eee18b_8  
brotli-python             1.0.9           py312h6a678d5_8  
brunsli                   0.1                  h2531618_0  
bzip2                     1.0.8                h5eee18b_6  
c-ares                    1.19.1               h5eee18b_0  
c-blosc2                  2.12.0               h80c7b02_0  
ca-certificates           2025.4.26            hbd8a1cb_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.3.3           py312h06a4308_0  
certifi                   2025.4.26          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py312h1fdaa30_0  
cfitsio                   3.470                h5893167_7  
chardet                   4.0.0           py312h06a4308_1003  
charls                    2.2.0                h2531618_0  
charset-normalizer        3.3.2              pyhd3eb1b0_0  
click                     8.1.7           py312h06a4308_0  
cloudpickle               3.0.0           py312h06a4308_0  
colorama                  0.4.6           py312h06a4308_0  
colorcet                  3.1.0           py312h06a4308_0  
comm                      0.2.1           py312h06a4308_0  
conda                     24.11.3         py312h7900ff3_0    conda-forge
conda-build               24.9.0          py312h06a4308_0  
conda-content-trust       0.2.0           py312h06a4308_1  
conda-index               0.5.0           py312h06a4308_0  
conda-libmamba-solver     24.9.0             pyhd3eb1b0_0  
conda-pack                0.7.1           py312h06a4308_0  
conda-package-handling    2.3.0           py312h06a4308_0  
conda-package-streaming   0.10.0          py312h06a4308_0  
conda-repo-cli            1.0.114         py312h06a4308_0  
conda-token               0.5.0              pyhd3eb1b0_0  
constantly                23.10.4         py312h06a4308_0  
contourpy                 1.2.0           py312hdb19cb5_0  
cookiecutter              2.6.0           py312h06a4308_0  
cryptography              43.0.0          py312hdda0065_0  
cssselect                 1.2.0           py312h06a4308_0  
cuda-cccl_linux-64        12.2.140             ha770c72_0    conda-forge
cuda-crt-dev_linux-64     12.2.140             ha770c72_1    conda-forge
cuda-crt-tools            12.2.140             ha770c72_1    conda-forge
cuda-cudart               12.2.140             hd3aeb46_0    conda-forge
cuda-cudart-dev           12.2.140             hd3aeb46_0    conda-forge
cuda-cudart-dev_linux-64  12.2.140             h59595ed_0    conda-forge
cuda-cudart-static        12.2.140             hd3aeb46_0    conda-forge
cuda-cudart-static_linux-64 12.2.140             h59595ed_0    conda-forge
cuda-cudart_linux-64      12.2.140             h59595ed_0    conda-forge
cuda-driver-dev_linux-64  12.2.140             h59595ed_0    conda-forge
cuda-nvcc                 12.2.140             hcdd1206_0    conda-forge
cuda-nvcc-dev_linux-64    12.2.140             ha770c72_1    conda-forge
cuda-nvcc-impl            12.2.140             hd3aeb46_1    conda-forge
cuda-nvcc-tools           12.2.140             hd3aeb46_1    conda-forge
cuda-nvcc_linux-64        12.2.140             h8a487aa_0    conda-forge
cuda-nvrtc                12.2.140             hd3aeb46_0    conda-forge
cuda-nvvm-dev_linux-64    12.2.140             ha770c72_1    conda-forge
cuda-nvvm-impl            12.2.140             h59595ed_1    conda-forge
cuda-nvvm-tools           12.2.140             h59595ed_1    conda-forge
cuda-version              12.2                 he2b69de_3    conda-forge
cupy                      13.4.1          py312h78400a1_0    conda-forge
cupy-core                 13.4.1          py312h007fbcc_0    conda-forge
curl                      8.9.1                hdbd6064_0  
cycler                    0.11.0             pyhd3eb1b0_0  
cyrus-sasl                2.1.28               h52b45da_1  
cytoolz                   0.12.2          py312h5eee18b_0  
dask                      2024.8.2        py312h06a4308_0  
dask-core                 2024.8.2        py312h06a4308_0  
dask-expr                 1.1.13          py312h06a4308_0  
datashader                0.16.3          py312h06a4308_0  
dav1d                     1.2.1                h5eee18b_0  
dbus                      1.13.18              hb2f20db_0  
debugpy                   1.6.7           py312h6a678d5_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713           pyhd3eb1b0_0  
dill                      0.3.8           py312h06a4308_0  
distributed               2024.8.2        py312h06a4308_0  
distro                    1.9.0           py312h06a4308_0  
docstring-to-markdown     0.11            py312h06a4308_0  
docutils                  0.18.1          py312h06a4308_3  
et_xmlfile                1.1.0           py312h06a4308_1  
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.7.0                h5888daf_0    conda-forge
fastrlock                 0.8.3           py312h6edf5ed_1    conda-forge
fbpic                     0.26.1                   pypi_0    pypi
filelock                  3.13.1          py312h06a4308_0  
flake8                    7.0.0           py312h06a4308_0  
flask                     3.0.3           py312h06a4308_0  
fmt                       9.1.0                hdb19cb5_1  
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonttools                 4.51.0          py312h5eee18b_0  
freetype                  2.12.1               h4a9f257_0  
frozendict                2.4.2           py312h06a4308_0  
frozenlist                1.4.0           py312h5eee18b_0  
fsspec                    2024.6.1        py312h06a4308_0  
gcc_impl_linux-64         12.4.0               h26ba24d_2    conda-forge
gcc_linux-64              12.4.0              h6b7512a_10    conda-forge
gensim                    4.3.2           py312hfb8ada1_1    conda-forge
gflags                    2.2.2                h6a678d5_1  
giflib                    5.2.1                h5eee18b_3  
gitdb                     4.0.7              pyhd3eb1b0_0  
gitpython                 3.1.43          py312h06a4308_0  
glib                      2.78.4               h6a678d5_0  
glib-tools                2.78.4               h6a678d5_0  
glog                      0.5.0                h6a678d5_1  
greenlet                  3.0.1           py312h6a678d5_0  
gst-plugins-base          1.14.1               h6a678d5_1  
gstreamer                 1.14.1               h5eee18b_1  
gxx_impl_linux-64         12.4.0               h3ff227c_2    conda-forge
gxx_linux-64              12.4.0              h8489865_10    conda-forge
h11                       0.14.0          py312h06a4308_0  
h5py                      3.13.0          nompi_py312hedeef09_100    conda-forge
hdf5                      1.14.3          nompi_hdf9ad27_105    conda-forge
heapdict                  1.0.1              pyhd3eb1b0_0  
holoviews                 1.19.1          py312h06a4308_0  
httpcore                  1.0.2           py312h06a4308_0  
httpx                     0.27.0          py312h06a4308_0  
hvplot                    0.11.0          py312h06a4308_0  
hyperlink                 21.0.0             pyhd3eb1b0_0  
icu                       73.1                 h6a678d5_0  
idna                      3.7             py312h06a4308_0  
imagecodecs               2023.1.23       py312h81b8100_1  
imageio                   2.33.1          py312h06a4308_0  
imagesize                 1.4.1           py312h06a4308_0  
imbalanced-learn          0.12.3          py312h06a4308_1  
importlib-metadata        7.0.1           py312h06a4308_0  
incremental               22.10.0            pyhd3eb1b0_0  
inflection                0.5.1           py312h06a4308_1  
iniconfig                 1.1.1              pyhd3eb1b0_0  
intake                    2.0.7           py312h06a4308_0  
intel-openmp              2023.1.0         hdb19cb5_46306  
intervaltree              3.1.0              pyhd3eb1b0_0  
ipykernel                 6.28.0          py312h06a4308_0  
ipython                   8.27.0          py312h06a4308_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.8.1           py312h06a4308_0  
isort                     5.13.2          py312h06a4308_0  
itemadapter               0.3.0              pyhd3eb1b0_0  
itemloaders               1.1.0           py312h06a4308_0  
itsdangerous              2.2.0           py312h06a4308_0  
jaraco.classes            3.2.1              pyhd3eb1b0_0  
jedi                      0.19.1          py312h06a4308_0  
jeepney                   0.7.1              pyhd3eb1b0_0  
jellyfish                 1.0.1           py312hb02cf49_0  
jinja2                    3.1.4           py312h06a4308_0  
jmespath                  1.0.1           py312h06a4308_0  
joblib                    1.4.2           py312h06a4308_0  
jpeg                      9e                   h5eee18b_3  
jq                        1.6               h27cfd23_1000  
json5                     0.9.6              pyhd3eb1b0_0  
jsonpatch                 1.33            py312h06a4308_1  
jsonpointer               2.1                pyhd3eb1b0_0  
jsonschema                4.23.0          py312h06a4308_0  
jsonschema-specifications 2023.7.1        py312h06a4308_0  
jupyter                   1.0.0           py312h06a4308_9  
jupyter-lsp               2.2.0           py312h06a4308_0  
jupyter_client            8.6.0           py312h06a4308_0  
jupyter_console           6.6.3           py312h06a4308_1  
jupyter_core              5.7.2           py312h06a4308_0  
jupyter_events            0.10.0          py312h06a4308_0  
jupyter_server            2.14.1          py312h06a4308_0  
jupyter_server_terminals  0.4.4           py312h06a4308_1  
jupyterlab                4.2.5           py312h06a4308_0  
jupyterlab-variableinspector 3.1.0           py312h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.27.3          py312h06a4308_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
jxrlib                    1.1                  h7b6447c_2  
kernel-headers_linux-64   3.10.0              he073ed8_18    conda-forge
keyring                   24.3.1          py312h06a4308_0  
kiwisolver                1.4.4           py312h6a678d5_0  
krb5                      1.20.1               h143b758_1  
lazy-object-proxy         1.10.0          py312h5eee18b_0  
lazy_loader               0.4             py312h06a4308_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.40                 h12ee557_0  
lerc                      3.0                  h295c915_0  
libabseil                 20240116.2      cxx17_h6a678d5_0  
libaec                    1.1.3                h59595ed_0    conda-forge
libarchive                3.7.4                hfab0078_0    main
libavif                   0.11.1               h5eee18b_0  
libblas                   3.9.0            20_linux64_mkl    conda-forge
libboost                  1.82.0               h109eef0_2  
libbrotlicommon           1.0.9                h5eee18b_8  
libbrotlidec              1.0.9                h5eee18b_8  
libbrotlienc              1.0.9                h5eee18b_8  
libcap                    2.71                 h39aace5_0    conda-forge
libcblas                  3.9.0            20_linux64_mkl    conda-forge
libclang                  14.0.6          default_hc6dbbc7_1  
libclang13                14.0.6          default_he11475f_1  
libcublas                 12.2.5.6             hd3aeb46_0    conda-forge
libcufft                  11.0.8.103           hd3aeb46_0    conda-forge
libcups                   2.4.2                h2d74bed_1  
libcurand                 10.3.3.141           hd3aeb46_0    conda-forge
libcurl                   8.9.1                h251f7ec_0  
libcusolver               11.5.2.141           hd3aeb46_0    conda-forge
libcusparse               12.1.2.141           hd3aeb46_0    conda-forge
libdeflate                1.17                 h5eee18b_1  
libedit                   3.1.20230828         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libevent                  2.1.12               hdbd6064_1  
libexpat                  2.7.0                h5888daf_0    conda-forge
libfabric                 2.1.0                ha770c72_0    conda-forge
libfabric1                2.1.0                h14e6f36_0    conda-forge
libffi                    3.4.4                h6a678d5_1  
libgcc                    15.1.0               h767d61c_2    conda-forge
libgcc-devel_linux-64     12.4.0             h1762d19_102    conda-forge
libgcc-ng                 15.1.0               h69a702a_2    conda-forge
libgcrypt-lib             1.11.1               hb9d3cd8_0    conda-forge
libgfortran               15.1.0               h69a702a_2    conda-forge
libgfortran-ng            15.1.0               h69a702a_2    conda-forge
libgfortran5              15.1.0               hcea5267_2    conda-forge
libglib                   2.78.4               hdc74915_0  
libgomp                   15.1.0               h767d61c_2    conda-forge
libgpg-error              1.55                 h3f2d84a_0    conda-forge
libgrpc                   1.62.2               h2d74bed_0  
libhwloc                  2.11.2          default_h0d58e46_1001    conda-forge
libiconv                  1.16                 h5eee18b_3  
liblapack                 3.9.0            20_linux64_mkl    conda-forge
liblief                   0.12.3               h6a678d5_0  
libllvm14                 14.0.6               hecde1de_4  
liblzma                   5.8.1                hb9d3cd8_1    conda-forge
liblzma-devel             5.8.1                hb9d3cd8_1    conda-forge
libmamba                  1.5.11               hfe524e5_0  
libmambapy                1.5.11          py312haf1ee3a_0  
libnghttp2                1.57.0               h2d74bed_0  
libnl                     3.11.0               hb9d3cd8_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libnvjitlink              12.2.140             hd3aeb46_0    conda-forge
libpng                    1.6.39               h5eee18b_0  
libpq                     12.17                hdbd6064_0  
libprotobuf               4.25.3               he621ea3_0  
libsanitizer              12.4.0               ha732cd4_2    conda-forge
libsodium                 1.0.18               h7b6447c_0  
libsolv                   0.7.24               he621ea3_1  
libspatialindex           1.9.3                h2531618_0  
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libssh2                   1.11.0               h251f7ec_0  
libstdcxx                 15.1.0               h8f9b012_2    conda-forge
libstdcxx-devel_linux-64  12.4.0             h1762d19_102    conda-forge
libstdcxx-ng              15.1.0               h4852527_2    conda-forge
libsystemd0               256.9                h2774228_0    conda-forge
libthrift                 0.15.0               h1795dd8_2  
libtiff                   4.5.1                h6a678d5_0  
libudev1                  257.4                h9a4d06a_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.2                h5eee18b_0  
libxcb                    1.15                 h7f8727e_0  
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxkbcommon              1.7.0                h662e7e4_0    conda-forge
libxml2                   2.13.8               hfdd30dd_0  
libxslt                   1.1.39               h76b75d6_0    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
libzopfli                 1.0.3                he6710b0_0  
linkify-it-py             2.0.0           py312h06a4308_0  
llvm-openmp               20.1.6               h024ca30_0    conda-forge
llvmlite                  0.44.0          py312hc1e8f15_1  
locket                    1.0.0           py312h06a4308_0  
lxml                      5.2.2           py312hb90d8a5_0    conda-forge
lz4                       4.3.2           py312h5eee18b_0  
lz4-c                     1.9.4                h6a678d5_1  
lzo                       2.10                 h7b6447c_2  
markdown                  3.4.1           py312h06a4308_0  
markdown-it-py            2.2.0           py312h06a4308_1  
markupsafe                2.1.3           py312h5eee18b_0  
matplotlib                3.9.2           py312h06a4308_0  
matplotlib-base           3.9.2           py312h66fe004_0  
matplotlib-inline         0.1.6           py312h06a4308_0  
mccabe                    0.7.0              pyhd3eb1b0_0  
mdit-py-plugins           0.3.0           py312h06a4308_0  
mdurl                     0.1.0           py312h06a4308_0  
menuinst                  2.1.2           py312h06a4308_0  
mistune                   2.0.4           py312h06a4308_0  
mkl                       2023.2.0         h84fe81f_50496    conda-forge
mkl-service               2.4.0           py312h5eee18b_1  
mkl_fft                   1.3.10          py312h5eee18b_0  
mkl_random                1.2.7           py312h526ad5a_0  
more-itertools            10.3.0          py312h06a4308_0  
mpi                       1.0.1                     mpich    conda-forge
mpi4py                    4.0.3           py312hcfe685a_101    conda-forge
mpich                     4.3.0              h1a8bee6_100    conda-forge
mpmath                    1.3.0           py312h06a4308_0  
msgpack-python            1.0.3           py312hdb19cb5_0  
multidict                 6.0.4           py312h5eee18b_0  
multipledispatch          0.6.0           py312h06a4308_0  
mypy                      1.11.2          py312h5eee18b_0  
mypy_extensions           1.0.0           py312h06a4308_0  
mysql                     5.7.24               h721c034_2  
navigator-updater         0.5.1           py312h06a4308_0  
nbclient                  0.8.0           py312h06a4308_0  
nbconvert                 7.16.4          py312h06a4308_0  
nbformat                  5.10.4          py312h06a4308_0  
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.6.0           py312h06a4308_0  
networkx                  3.3             py312h06a4308_0  
nltk                      3.9.1           py312h06a4308_0  
notebook                  7.2.2           py312h06a4308_1  
notebook-shim             0.2.3           py312h06a4308_0  
nspr                      4.35                 h6a678d5_0  
nss                       3.89.1               h6a678d5_0  
numba                     0.61.2          py312h2e6246c_0    conda-forge
numexpr                   2.8.7           py312hf827012_0  
numpy                     1.26.4          py312hc5e2394_0  
numpy-base                1.26.4          py312h0da6c21_0  
numpydoc                  1.7.0           py312h06a4308_0  
nvidia-ml-py              12.575.51          pyhd8ed1ab_0    conda-forge
oniguruma                 6.9.7.1              h27cfd23_0  
openjpeg                  2.5.2                he7f1fd0_0  
openpyxl                  3.1.5           py312h5eee18b_0  
openssl                   3.5.0                h7b32b05_1    conda-forge
orc                       2.0.1                h2d29ad5_0  
overrides                 7.4.0           py312h06a4308_0  
packaging                 24.1            py312h06a4308_0  
pandas                    2.2.2           py312h526ad5a_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
panel                     1.5.2           py312h06a4308_0  
param                     2.1.1           py312h06a4308_0  
parsel                    1.8.1           py312h06a4308_0  
parso                     0.8.3              pyhd3eb1b0_0  
partd                     1.4.1           py312h06a4308_0  
patch                     2.7.6             h7b6447c_1001  
patchelf                  0.17.2               h6a678d5_0  
pathspec                  0.10.3          py312h06a4308_0  
patsy                     0.5.6           py312h06a4308_0  
pcre2                     10.42                hebb0a14_1  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    10.4.0          py312h5eee18b_0  
pip                       24.2            py312h06a4308_0  
pkce                      1.0.3           py312h06a4308_0  
pkginfo                   1.10.0          py312h06a4308_0  
platformdirs              3.10.0          py312h06a4308_0  
plotly                    5.24.1          py312he106c6f_0  
pluggy                    1.0.0           py312h06a4308_1  
ply                       3.11            py312h06a4308_1  
prometheus_client         0.14.1          py312h06a4308_0  
prompt-toolkit            3.0.43          py312h06a4308_0  
prompt_toolkit            3.0.43               hd3eb1b0_0  
protego                   0.1.16                     py_0  
protobuf                  4.25.3          py312h12ddb61_0  
psutil                    5.9.0           py312h5eee18b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
py-cpuinfo                9.0.0           py312h06a4308_0  
py-lief                   0.12.3          py312h6a678d5_0  
pyarrow                   16.1.0          py312h526ad5a_0  
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pybind11-abi              5                    hd3eb1b0_0  
pycodestyle               2.11.1          py312h06a4308_0  
pycosat                   0.6.6           py312h5eee18b_1  
pycparser                 2.21               pyhd3eb1b0_0  
pyct                      0.5.0           py312h06a4308_0  
pycurl                    7.45.3          py312hdbd6064_0  
pydantic                  2.8.2           py312h06a4308_0  
pydantic-core             2.20.1          py312hb02cf49_0  
pydeck                    0.8.0           py312h06a4308_2  
pydispatcher              2.0.5           py312h06a4308_3  
pydocstyle                6.3.0           py312h06a4308_0  
pyerfa                    2.0.1.4         py312ha883a20_0  
pyflakes                  3.2.0           py312h06a4308_0  
pygments                  2.15.1          py312h06a4308_1  
pyjwt                     2.8.0           py312h06a4308_0  
pylint                    2.16.2          py312h06a4308_0  
pylint-venv               3.0.3           py312h06a4308_0  
pyls-spyder               0.4.0              pyhd3eb1b0_0  
pynvml                    12.0.0             pyhd8ed1ab_0    conda-forge
pyodbc                    5.1.0           py312h6a678d5_0  
pyopenssl                 24.2.1          py312h06a4308_0  
pyparsing                 3.1.2           py312h06a4308_0  
pyqt                      5.15.10         py312h6a678d5_0  
pyqt5-sip                 12.13.0         py312h5eee18b_0  
pyqtwebengine             5.15.10         py312h6a678d5_0  
pysocks                   1.7.1           py312h06a4308_0  
pytables                  3.9.2           py312h5531bb7_1    conda-forge
pytest                    7.4.4           py312h06a4308_0  
python                    3.12.2          hab00c5b_0_cpython    conda-forge
python-dateutil           2.9.0post0      py312h06a4308_2  
python-dotenv             0.21.0          py312h06a4308_0  
python-fastjsonschema     2.16.2          py312h06a4308_0  
python-json-logger        2.0.7           py312h06a4308_0  
python-libarchive-c       5.1                pyhd3eb1b0_0  
python-lmdb               1.4.1           py312h6a678d5_0  
python-lsp-black          2.0.0           py312h06a4308_0  
python-lsp-jsonrpc        1.1.2              pyhd3eb1b0_0  
python-lsp-server         1.10.0          py312h06a4308_0  
python-slugify            5.0.2              pyhd3eb1b0_0  
python-tzdata             2023.3             pyhd3eb1b0_0  
python_abi                3.12                    7_cp312    conda-forge
pytoolconfig              1.2.6           py312h06a4308_0  
pytz                      2024.1          py312h06a4308_0  
pyviz_comms               3.0.2           py312h06a4308_0  
pywavelets                1.7.0           py312h5eee18b_0  
pyxdg                     0.27               pyhd3eb1b0_0  
pyyaml                    6.0.1           py312h5eee18b_0  
pyzmq                     25.1.2          py312h6a678d5_0  
qdarkstyle                3.2.3              pyhd3eb1b0_0  
qstylizer                 0.2.2           py312h06a4308_0  
qt-main                   5.15.2              h53bd1ea_10  
qt-webengine              5.15.9               he2071f7_8  
qtawesome                 1.3.1           py312h06a4308_0  
qtconsole                 5.5.1           py312h06a4308_0  
qtpy                      2.4.1           py312h06a4308_0  
queuelib                  1.6.2           py312h06a4308_0  
rdma-core                 55.0                 h5888daf_0    conda-forge
re2                       2022.04.01           h295c915_0  
readline                  8.2                  h5eee18b_0  
referencing               0.30.2          py312h06a4308_0  
regex                     2024.9.11       py312h5eee18b_0  
reproc                    14.2.4               h6a678d5_2  
reproc-cpp                14.2.4               h6a678d5_2  
requests                  2.32.3          py312h06a4308_0  
requests-file             1.5.1              pyhd3eb1b0_0  
requests-toolbelt         1.0.0           py312h06a4308_0  
rfc3339-validator         0.1.4           py312h06a4308_0  
rfc3986-validator         0.1.1           py312h06a4308_0  
rich                      13.7.1          py312h06a4308_0  
rope                      1.12.0          py312h06a4308_0  
rpds-py                   0.10.6          py312hb02cf49_0  
rtree                     1.0.1           py312h06a4308_0  
ruamel.yaml               0.18.6          py312h5eee18b_0  
ruamel.yaml.clib          0.2.8           py312h5eee18b_0  
ruamel_yaml               0.17.21         py312h5eee18b_0  
s2n                       1.3.27               hdbd6064_0  
s3fs                      2024.6.1        py312h06a4308_0  
scikit-image              0.24.0          py312h526ad5a_0  
scikit-learn              1.5.1           py312h526ad5a_0  
scipy                     1.15.2          py312ha707e6e_0    conda-forge
scrapy                    2.11.1          py312h06a4308_0  
seaborn                   0.13.2          py312h06a4308_0  
secretstorage             3.3.1           py312h06a4308_1  
semver                    3.0.2           py312h06a4308_0  
send2trash                1.8.2           py312h06a4308_0  
service_identity          18.1.0             pyhd3eb1b0_1  
setuptools                75.1.0          py312h06a4308_0  
sip                       6.7.12          py312h6a678d5_0  
six                       1.16.0             pyhd3eb1b0_1  
smart_open                5.2.1           py312h06a4308_0  
smmap                     4.0.0              pyhd3eb1b0_0  
snappy                    1.2.1                h6a678d5_0  
sniffio                   1.3.0           py312h06a4308_0  
snowballstemmer           2.2.0              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.5             py312h06a4308_0  
sphinx                    7.3.7           py312h5eee18b_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.10          py312h06a4308_0  
spyder                    5.5.1           py312h06a4308_4  
spyder-kernels            2.5.0           py312h06a4308_0  
sqlalchemy                2.0.34          py312h00e1ef3_0  
sqlite                    3.45.3               h5eee18b_0  
stack_data                0.2.0              pyhd3eb1b0_0  
statsmodels               0.14.2          py312ha883a20_0  
streamlit                 1.37.1          py312h06a4308_0  
sympy                     1.13.2          py312h06a4308_0  
sysroot_linux-64          2.17                h0157908_18    conda-forge
tabulate                  0.9.0           py312h06a4308_0  
tbb                       2021.8.0             hdb19cb5_0  
tblib                     1.7.0              pyhd3eb1b0_0  
tenacity                  8.2.3           py312h06a4308_0  
terminado                 0.17.1          py312h06a4308_0  
text-unidecode            1.3                pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
threadpoolctl             3.5.0           py312he106c6f_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tifffile                  2023.4.12       py312h06a4308_0  
tinycss2                  1.2.1           py312h06a4308_0  
tk                        8.6.14               h39e8969_0  
tldextract                5.1.2           py312h06a4308_0  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1           py312h06a4308_1  
tomlkit                   0.11.1          py312h06a4308_0  
toolz                     0.12.0          py312h06a4308_0  
tornado                   6.4.1           py312h5eee18b_0  
tqdm                      4.66.5          py312he106c6f_0  
traitlets                 5.14.3          py312h06a4308_0  
truststore                0.8.0           py312h06a4308_0  
twisted                   23.10.0         py312h06a4308_0  
typing-extensions         4.11.0          py312h06a4308_0  
typing_extensions         4.11.0          py312h06a4308_0  
tzdata                    2024b                h04d1e81_0  
uc-micro-py               1.0.1           py312h06a4308_0  
ucx                       1.18.0               h8887438_3    conda-forge
ujson                     5.10.0          py312h6a678d5_0  
unicodedata2              15.1.0          py312h5eee18b_0  
unidecode                 1.3.8           py312h06a4308_0  
unixodbc                  2.3.11               h5eee18b_0  
urllib3                   2.2.3           py312h06a4308_0  
utf8proc                  2.6.1                h5eee18b_1  
w3lib                     1.21.0             pyhd3eb1b0_0  
watchdog                  4.0.1           py312h06a4308_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1           py312h06a4308_2  
websocket-client          1.8.0           py312h06a4308_0  
werkzeug                  3.0.3           py312h06a4308_0  
whatthepatch              1.0.2           py312h06a4308_0  
wheel                     0.44.0          py312h06a4308_0  
widgetsnbextension        3.6.6           py312h06a4308_0  
wrapt                     1.14.1          py312h5eee18b_0  
wurlitzer                 3.0.2           py312h06a4308_0  
xarray                    2023.6.0        py312h06a4308_0  
xkeyboard-config          2.42                 h4ab18f5_0    conda-forge
xorg-kbproto              1.0.7             hb9d3cd8_1003    conda-forge
xorg-libx11               1.8.9                h8ee46fc_0    conda-forge
xorg-libxau               1.0.12               hb9d3cd8_0    conda-forge
xorg-xextproto            7.3.0             hb9d3cd8_1004    conda-forge
xorg-xproto               7.0.31            hb9d3cd8_1008    conda-forge
xyzservices               2022.9.0        py312h06a4308_1  
xz                        5.8.1                hbcc6ac9_1    conda-forge
xz-gpl-tools              5.8.1                hbcc6ac9_1    conda-forge
xz-tools                  5.8.1                hb9d3cd8_1    conda-forge
yaml                      0.2.5                h7b6447c_0  
yaml-cpp                  0.8.0                h6a678d5_1  
yapf                      0.40.2          py312h06a4308_0  
yarl                      1.11.0          py312h5eee18b_0  
zeromq                    4.3.5                h6a678d5_0  
zfp                       1.0.0                h6a678d5_0  
zict                      3.0.0           py312h06a4308_0  
zipp                      3.17.0          py312h06a4308_0  
zlib                      1.2.13               h4ab18f5_6    conda-forge
zlib-ng                   2.0.7                h5eee18b_0  
zope                      1.0             py312h06a4308_1  
zope.interface            5.4.0           py312h5eee18b_0  
zstandard                 0.23.0          py312h2c38b39_0  
zstd                      1.5.6                hc292b87_0
```

**Comment by plasmahomie** [comment]
It has turned out that the reinstall did not fix the issue, but instead it was a hardware issue on the cluster I am using. So I will close this issue now, and my advice to anyone with the same problem is to go straight to your cluster support team!
